### ISSUE TITLE
Cannot delete order (customer page)

### ISSUE THREAD

**Issue by MarshallCN** [EADG6/CWMS#18]
- customer cannot delete appoint order
- admin page could see the empty order block
![](https://trello-attachments.s3.amazonaws.com/583ad61452ccaf2c8de33f12/59127cdff626ae9b25c36b8b/a4cb6ccc65429333b91e3537ab34433a/%E6%8D%95%E8%8E%B7.PNG)

**Comment by leo-lizhuoxuan** [comment]
I modification now
