### ISSUE TITLE
Something could be improve in website

### ISSUE THREAD

**Issue by MarshallCN** [EADG6/CWMS#2]
![image](https://cloud.githubusercontent.com/assets/16070638/23807831/30bda03a-0602-11e7-89c6-df80a1b96d03.png)
## **1. forms group style could be changed into the one below** 
![image](https://cloud.githubusercontent.com/assets/16070638/23807893/810a583a-0602-11e7-9c32-521cc0336eee.png)
## **2. Footer is different wrong**
![image](https://cloud.githubusercontent.com/assets/16070638/23807979/de447698-0602-11e7-95c6-77360f75ca96.png)

**Comment by MarshallCN** [comment]
@leo-lizhuoxuan  @qq398935137  Anyone can fix these issue??

**Comment by MarshallCN** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIX Issues in github !!!](https://trello.com/c/hEa581y8/56-fix-issues-in-github)

**Comment by qq398935137** [comment]
solved it

**Comment by MarshallCN** [comment]
Well done
