### ISSUE TITLE
home page 

### ISSUE THREAD

**Issue by leo-lizhuoxuan** [EADG6/CWMS#7]
@qq398935137 
**Add information in Home page**
<img width="1278" alt="2017-03-20 19 32 09" src="https://cloud.githubusercontent.com/assets/26318938/24098953/f1f05912-0da7-11e7-8e4b-78d6ddd40f45.png">
add company picture
 
<img width="1257" alt="2017-03-20 19 32 19" src="https://cloud.githubusercontent.com/assets/26318938/24099320/7f4170ca-0da9-11e7-994b-5625d7557930.png">

change customer information

<img width="1230" alt="2017-03-20 19 32 24" src="https://cloud.githubusercontent.com/assets/26318938/24105487/fcdddd3c-0dbf-11e7-94ee-3fa75f4bc04c.png">

add staff information

**Comment by qq398935137** [comment]
the specific information should be written by cary @leo-lizhuoxuan @CaryTian

**Comment by CaryTian** [comment]
I will bring some information  tomorrow for you
