### ISSUE TITLE
Change "News" Page in front-end

### ISSUE THREAD

**Issue by MarshallCN** [EADG6/CWMS#8]
Current News Page:
![2017-03-22_152511](https://cloud.githubusercontent.com/assets/16070638/24186920/8d87db8e-0f15-11e7-91ff-77eba43c26c2.jpg)

1. **Make a list of news**
2. **Dont COPY other news**
 @leo-lizhuoxuan @qq398935137 
3. **Give us some your own articles**
@CaryTian

**Comment by qq398935137** [comment]
i think we can delete the news page, not very useful.

**Comment by MarshallCN** [comment]
what do u think? @leo-lizhuoxuan @CaryTian

**Comment by CaryTian** [comment]
I have bring some new photos for now the CWS
